name: My Docker Image CI

on:
  push:
    branches: [ release ]

jobs:
  
  checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: release

  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sherweipng/myfirstimg:1.0


      - 
        name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": 
                    {
                      "type": "mrkdwn",
                      "text": "Name: Png Sher Wei"
                    },
                  "text": 
                    {
                      "type": "mrkdwn",
                      "text": "Matriculation: A0044651L"
                    },
                  "text": 
                    {
                      "type": "mrkdwn",
                      "text": "Email: e0941860@u.nus.edu"
                    },
                  "text": 
                    {
                      "type": "mrkdwn",
                      "text": "Repo: <github.com/sherweipng/randnum|git@github.com/sherweipng/randnum.git>"
                    },
                  "text": 
                    {
                      "type": "mrkdwn",
                      "text": "Image name: sherweipng/myfirstimg:1.0"
                    },
                  "text": 
                    {
                      "type": "mrkdwn",
                      "text": "Image url: <https://hub.docker.com/repository/docker/sherweipng/myfirstimg|https://hub.docker.com/repository/docker/sherweipng/myfirstimg>"
                    }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK